### ISSUE TITLE
Possibility to remove "Only Necessary" button and "Configure Settings" button

### ISSUE THREAD

**Issue by intelligence** [bernskioldmedia/Ilmenite-Cookie-Consent#18]
Like in the screenshots for the plugin. I guess I can hide them with css, but does feel a bit unclean.

**Comment by ErikBernskiold** [comment]
Hi @intelligence, sorry for having missed your issue. I'm afraid that's our bad for not updating the screenshots. The two buttons are a newer feature in the latest version and cannot be disabled to comply with the latest ruling on privacy regulation.

We are considering allowing you to toggle which sections (necessary, marketing, statistics) to enable and if/when done, if you don't have any marketing or statistics cookies then we'd only present the one button.

Thanks for your feedback!
