### ISSUE TITLE
not blocking 3rd-party-domains

### ISSUE THREAD

**Issue by gitalexa** [bernskioldmedia/Ilmenite-Cookie-Consent#32]
i added the domains fonts.gstatic.com and www.gstatic.com to the marketing list of the tracker tool. 

So i expected that this domains will be blocked until the user has allowed it. But the browser ist calling this domains on loading the page.

**Comment by ErikBernskiold** [comment]
This is because font includes are using `<link>` to connect. This plugin only supports scripts loaded via `<script>` I'm afraid.
