### ISSUE TITLE
Downloads are incomplete

### ISSUE THREAD

**Issue by crstauf** [bernskioldmedia/Ilmenite-Cookie-Consent#81]
Not sure if this plugin is being maintained or not, but I found it and tried to install. Whenever downloading the repository, assets are missing. There are source files, but they're not built.

**Comment by ErikBernskiold** [comment]
Hi @crstauf. It is being maintained! The officially supported way of installing the plugin is through the WP.org repo: https://wordpress.org/plugins/ilmenite-cookie-consent/

**Comment by crstauf** [comment]
Thanks, @ErikBernskiold. I looked for a URL on the repo, but didn't find it. Should've search the WP.org repository. Thanks!
